channels:
- conda-forge
dependencies:
- anywidget
- esbuild
- matplotlib
- numpy
- ipython
- ipywidgets
- jupyterlab
- pyiron_workflow
- scipy
- pip
- pip:
  - git+https://github.com/pyiron/pyiron_nodes.git
