[build-system]
requires = [
    "hatchling==1.28.0",
    "hatch-jupyter-builder>=0.9.1",
    "hatch-vcs==0.5.0"
]
build-backend = "hatchling.build"

[project]
name = "pyironflow"
description = "react xyflow for pyiron"
authors = [
    { name = "Max-Planck-Institut für Nachhaltige Materialien GmbH - Computational Materials Design (CM) Department", email = "pyiron@mpie.de" },
]
readme = "docs/README.md"
license = { file = "LICENSE" }
keywords = ["pyiron"]
requires-python = ">=3.11, <3.14"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "anywidget==0.9.18",
    "ipytree==0.2.2",
    "ipython==8.37.0",
    "ipywidgets==8.1.8",
    "pyiron_workflow==0.17.0",
    "traitlets==5.14.3"
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/pyiron/pyironFlow"
Documentation = "https://github.com/pyiron/pyironFlow"
Repository = "https://github.com/pyiron/pyironFlow"

[project.optional-dependencies]
dev = [
    "esbuild==0.27.2",
    "jupyterlab",
    "watchfiles"
]

[tool.hatch.envs.default]
features = ["dev"]

[tool.hatch.build]
only-packages = true
artifacts = [
    "pyironflow/*",
    "pyironflow/static/*"
]

[tool.hatch.build.targets.sdist]
include = [
    "pyironflow",
    "js",
    "package.json",
    "package-lock.json"
]

[tool.hatch.build.targets.wheel]
packages = ["pyironflow"]

[tool.hatch.build.hooks.jupyter-builder]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = ["pyironflow/static/widget.js"]
skip-if-exists = ["pyironflow/static/widget.js"]
dependencies = ["hatch-jupyter-builder>=0.5.0"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
npm = "npm"
build_cmd = "build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "pyironflow/_version.py"

[tool.ruff]
exclude = ["docs", "notebooks"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501"] #ignore line-length violations

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in init files -- we specify APIs this way

[tool.black]
extend-exclude = '''
(
  ^/docs
)
'''
