channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- anywidget =0.9.18
- esbuild =0.27.2
- hatchling =1.28.0
- hatch-jupyter-builder =0.9.1
- hatch-vcs =0.5.0
- ipython =8.37.0
- ipytree =0.2.2
- ipywidgets =8.1.8
- nodejs =25.2.1
- pyiron_workflow =0.16.0
- traitlets =5.14.3
