# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-main-Pull-all

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@actions-4.2.1
    secrets: inherit
    with:
      python-version-alt1: '3.11'
      python-version-alt2: '3.12'
      python-version: '3.13'
      notebooks-env-files: .ci_support/environment.yml .ci_support/environment-binder.yml
      do-commit-updated-env: true
      do-build-docs: true
      do-build-notebooks: true
      do-unit-tests: true
      do-codecov: false
      do-codacy: false
      do-coveralls: false
      do-benchmark-tests: true
      do-pip-check: true
      do-black: true
      do-ruff-check: true
      do-ruff-sort-imports: true
      do-mypy: false
