# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-main-Pull-all

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@actions-4.0.10
    secrets: inherit
    with:
      python-version: 3.12
      notebooks-env-files: .ci_support/environment.yml .ci_support/environment-binder.yml
      do-commit-updated-env: true
      do-build-docs: false
      do-build-notebooks: true
      do-unit-tests: false
      do-codecov: false
      do-codacy: false
      do-coveralls: false
      do-benchmark-tests: false
      do-pip-check: false
      do-black: false
      do-ruff-check: false
      do-ruff-sort-imports: false
      do-mypy: false
