name: Release

on:
  pull_request:
  release:
    types: [ published ]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/hatch-release.yml@actions-4.0.11
    secrets: inherit
    with:
      env-files: environment.yml
      semantic-upper-bound: 'minor'
      publish-to-pypi: ${{ github.event_name == 'release' && github.event.action == 'published' }}