name: ui-tests
on: pull_request

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pyiron/actions/cached-miniforge@actions-4.2.1
        with:
          python-version: "3.12"
          env-files: .ci_support/environment.yml .ci_support/environment-ui.yml
      - name: Install  # nodejs from environment.yml; hatch runs our build script
        shell: bash -l {0}
        run: python -m pip install pytest-ipywidgets
      - name: Install browser
        shell: bash -l {0}
        run: playwright install --with-deps chromium
      - name: Log playwright versions
        shell: bash -l {0}
        run: |
          conda list | grep -i playwright
          pip list | grep -i playwright
          python -c "import playwright, playwright._repo_version as v; print(playwright.__file__, v.version)"
          playwright --version
      - name: Run UI tests
        shell: bash -l {0}
        run: |
          python -m pytest tests/ui -v -rs --timeout=120 \
          --browser chromium \
          --video=retain-on-failure \
          --tracing=retain-on-failure \
          --output=test-results \
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results
          path: test-results